/**
 * @repo/inverter-adapters — Per-vendor monitoring API adapters for
 * solar inverters. Used by the Supabase Edge Function poller to
 * fetch readings into the partitioned inverter_readings table.
 *
 * Wiring: the poller calls `getAdapter(inverter.brand)`, passes in
 * credentials resolved from Supabase Vault, and upserts the resulting
 * NormalizedReading[] into the database.
 *
 * All adapters share a common interface (InverterAdapter) so the
 * poller has no vendor-specific branching. See base.ts for the
 * contract and normalization rules.
 *
 * Current implementation status:
 *   - sungrow: STUB (synthetic mode works, live HTTP TODO)
 *   - growatt: STUB (synthetic mode works, live HTTP TODO)
 *   - sma:     STUB (synthetic mode works)
 *   - huawei:  STUB (synthetic mode works)
 *   - fronius: falls back to sungrow stub until dedicated adapter exists
 *
 * Synthetic mode: set SYNTHETIC_INVERTER_READINGS=1 in the Edge Function
 * environment. All adapters will return plausible solar-curve data
 * generated by `syntheticReading(capacity)` in base.ts. This lets the
 * full telemetry pipeline (poller → upsert → rollup → auto-ticket) be
 * end-to-end tested before live vendor credentials arrive.
 */

export * from './base';
export { sungrowAdapter, mapSungrowStatus } from './sungrow';
export { growattAdapter, mapGrowattStatus } from './growatt';
export { smaAdapter } from './sma';
export { huaweiAdapter } from './huawei';
export { getAdapter, allBrands } from './factory';
