'use client';

/**
 * BOQ editable table (Tab 1).
 *
 * Competitive mode: select rows → "Send RFQ" → creates RFQ + routes to Tab 2.
 * Quick PO mode: select rows + single vendor → "Quick PO" → creates PO directly.
 * Inline edit: pencil icon → edit qty + rate for yet_to_place items.
 * Download: BOQ PDF button in action bar.
 *
 * Re-uses server actions from `procurement-actions.ts`.
 */

import * as React from 'react';
import { useRouter } from 'next/navigation';
import { Button } from '@repo/ui';
import { Send, Zap, Package, Pencil, Check, X } from 'lucide-react';
import { formatINR } from '@repo/ui/formatters';
import type { Database } from '@repo/types/database';
import type { PurchaseDetailItem } from '@/lib/procurement-queries';
import {
  bulkAssignVendor,
  createPOsFromAssignedItems,
  updateBoqItemQtyRate,
} from '@/lib/procurement-actions';
import { BoqDownloadButton } from '@/components/procurement/boq-download-button';

type AppRole = Database['public']['Enums']['app_role'];

interface BoqEditableTableProps {
  projectId: string;
  items: PurchaseDetailItem[];
  vendors: Array<{ id: string; company_name: string; phone: string | null; email: string | null; contact_person: string | null }>;
  viewerRole: AppRole;
  /** Full name of the viewer — passed to BOQ PDF "Generated by". */
  viewerName?: string;
  /** Project details for PDF header. */
  project?: { project_number: string; customer_name: string; site_address?: string | null };
}

function StatusPill({ status }: { status: string }) {
  const config: Record<string, { label: string; className: string }> = {
    yet_to_place: { label: 'Yet to Place', className: 'bg-amber-100 text-amber-700' },
    order_placed: { label: 'Ordered', className: 'bg-blue-100 text-blue-700' },
    received: { label: 'Received', className: 'bg-green-100 text-green-700' },
    ready_to_dispatch: { label: 'Ready', className: 'bg-purple-100 text-purple-700' },
    delivered: { label: 'Delivered', className: 'bg-n-200 text-n-700' },
  };
  const c = config[status] ?? { label: status, className: 'bg-n-100 text-n-600' };
  return (
    <span className={`inline-flex items-center px-1.5 py-0.5 rounded text-[9px] font-medium uppercase ${c.className}`}>
      {c.label}
    </span>
  );
}

const EDITABLE_ROLES: AppRole[] = ['founder', 'project_manager', 'purchase_officer'];

export function BoqEditableTable({
  projectId,
  items,
  vendors,
  viewerRole,
  viewerName = 'Shiroi ERP',
  project,
}: BoqEditableTableProps) {
  const router = useRouter();
  const [selected, setSelected] = React.useState<Set<string>>(new Set());
  const [saving, setSaving] = React.useState(false);
  const [quickPoVendor, setQuickPoVendor] = React.useState('');
  const [message, setMessage] = React.useState<string | null>(null);

  // Inline edit state
  const [editingId, setEditingId] = React.useState<string | null>(null);
  const [draft, setDraft] = React.useState<{ quantity: string; rate: string }>({ quantity: '', rate: '' });
  const [editSaving, setEditSaving] = React.useState(false);
  const [editError, setEditError] = React.useState<string | null>(null);

  const canEdit = EDITABLE_ROLES.includes(viewerRole);
  const assignable = items.filter((i) => i.procurement_status === 'yet_to_place');

  function toggleSelect(id: string) {
    setSelected((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }

  function selectAll() {
    if (selected.size === assignable.length) {
      setSelected(new Set());
    } else {
      setSelected(new Set(assignable.map((i) => i.id)));
    }
  }

  function handleSendRfq() {
    if (selected.size === 0) {
      setMessage('Select at least one BOQ item first');
      return;
    }
    try {
      sessionStorage.setItem(
        `rfq-preselect-${projectId}`,
        JSON.stringify(Array.from(selected)),
      );
    } catch {
      // sessionStorage may be disabled
    }
    router.push(`/procurement/project/${projectId}?tab=rfq`);
  }

  async function handleQuickPo() {
    if (!quickPoVendor) {
      setMessage('Select a vendor for Quick PO');
      return;
    }
    if (selected.size === 0) {
      setMessage('Select at least one BOQ item first');
      return;
    }
    if (!confirm(`Skip RFQ and create a Purchase Order for ${selected.size} items directly?`)) {
      return;
    }
    setSaving(true);
    setMessage(null);
    const assignRes = await bulkAssignVendor({
      boqItemIds: Array.from(selected),
      vendorId: quickPoVendor,
      projectId,
    });
    if (!assignRes.success) {
      setSaving(false);
      setMessage(assignRes.error ?? 'Vendor assignment failed');
      return;
    }
    const poRes = await createPOsFromAssignedItems({
      projectId,
      boqItemIds: Array.from(selected),
    });
    setSaving(false);
    if (poRes.success) {
      setMessage(`Created ${poRes.poCount} PO(s) — awaiting approval`);
      setSelected(new Set());
      setQuickPoVendor('');
      router.refresh();
    } else {
      setMessage(poRes.error ?? 'PO creation failed');
    }
  }

  function startEdit(item: PurchaseDetailItem) {
    setEditingId(item.id);
    setDraft({
      quantity: String(item.quantity),
      rate: String(item.unit_price),
    });
    setEditError(null);
  }

  function cancelEdit() {
    setEditingId(null);
    setEditError(null);
  }

  async function saveEdit(item: PurchaseDetailItem) {
    const qty = parseFloat(draft.quantity);
    const rate = parseFloat(draft.rate);
    if (!Number.isFinite(qty) || qty <= 0) {
      setEditError('Quantity must be > 0');
      return;
    }
    if (!Number.isFinite(rate) || rate < 0) {
      setEditError('Rate must be ≥ 0');
      return;
    }
    setEditSaving(true);
    setEditError(null);
    const res = await updateBoqItemQtyRate({
      boqItemId: item.id,
      quantity: qty,
      unitPrice: rate,
    });
    setEditSaving(false);
    if (!res.success) {
      setEditError(res.error);
      return;
    }
    setEditingId(null);
    router.refresh();
  }

  const selectedTotal = items
    .filter((i) => selected.has(i.id))
    .reduce((sum, i) => sum + Number(i.total_price || 0), 0);

  // Build items shape for PDF
  const pdfItems = items.map((i) => ({
    line_number: i.line_number,
    item_category: i.item_category,
    item_description: i.item_description,
    unit: i.unit,
    quantity: Number(i.quantity),
    unit_price: Number(i.unit_price),
    total_price: Number(i.total_price),
    hsn_code: i.hsn_code,
  }));

  const pdfProject = project ?? {
    project_number: projectId.slice(0, 8),
    customer_name: '',
    site_address: null,
  };

  return (
    <div>
      {/* Action bar */}
      <div className="flex items-center gap-2 flex-wrap px-3 py-2 border-b border-n-200 bg-n-50">
        <span className="text-[11px] text-n-700 font-medium">
          {selected.size > 0
            ? `${selected.size} selected · ${formatINR(selectedTotal)}`
            : `${assignable.length} items ready for purchase`}
        </span>

        <div className="w-px h-5 bg-n-200 mx-1" />

        {/* Competitive flow — Send RFQ */}
        <Button
          size="sm"
          className="h-7 text-[10px] px-2 gap-1"
          disabled={selected.size === 0 || saving}
          onClick={handleSendRfq}
        >
          <Send className="h-3 w-3" />
          Send RFQ ({selected.size})
        </Button>

        <div className="w-px h-5 bg-n-200 mx-1" />

        {/* Quick PO path — skip RFQ */}
        <label className="text-[10px] text-n-500 font-medium">Or Quick PO to:</label>
        <select
          value={quickPoVendor}
          onChange={(e) => setQuickPoVendor(e.target.value)}
          className="h-7 text-[11px] border border-n-200 rounded px-1.5 max-w-[180px]"
          disabled={saving}
        >
          <option value="">Select vendor...</option>
          {vendors.map((v) => (
            <option key={v.id} value={v.id}>{v.company_name}</option>
          ))}
        </select>
        <Button
          size="sm"
          variant="outline"
          className="h-7 text-[10px] px-2 gap-1"
          disabled={!quickPoVendor || selected.size === 0 || saving}
          onClick={handleQuickPo}
        >
          <Zap className="h-3 w-3" />
          {saving ? '...' : `Quick PO (${selected.size})`}
        </Button>

        <div className="w-px h-5 bg-n-200 mx-1" />

        {/* BOQ PDF download */}
        <BoqDownloadButton
          project={pdfProject}
          items={pdfItems}
          generatedBy={viewerName}
        />

        {message && (
          <span className="text-[10px] text-p-600 font-medium ml-auto">{message}</span>
        )}
      </div>

      {/* Items table */}
      <div className="overflow-x-auto">
        <table className="w-full">
          <thead>
            <tr className="border-b border-n-200 bg-n-50 text-left">
              <th className="px-2 py-1.5 w-8">
                {assignable.length > 0 && (
                  <input
                    type="checkbox"
                    checked={selected.size === assignable.length && assignable.length > 0}
                    onChange={selectAll}
                    className="h-3 w-3"
                  />
                )}
              </th>
              <th className="px-2 py-1.5 text-[10px] font-semibold text-n-500 uppercase w-8">#</th>
              <th className="px-2 py-1.5 text-[10px] font-semibold text-n-500 uppercase">Category</th>
              <th className="px-2 py-1.5 text-[10px] font-semibold text-n-500 uppercase">Description</th>
              <th className="px-2 py-1.5 text-[10px] font-semibold text-n-500 uppercase">HSN</th>
              <th className="px-2 py-1.5 text-[10px] font-semibold text-n-500 uppercase text-right">Qty</th>
              <th className="px-2 py-1.5 text-[10px] font-semibold text-n-500 uppercase text-right">Rate</th>
              <th className="px-2 py-1.5 text-[10px] font-semibold text-n-500 uppercase text-right">Total</th>
              <th className="px-2 py-1.5 text-[10px] font-semibold text-n-500 uppercase">Status</th>
              <th className="px-2 py-1.5 text-[10px] font-semibold text-n-500 uppercase">Vendor</th>
              {canEdit && (
                <th className="px-2 py-1.5 w-8" aria-label="Edit" />
              )}
            </tr>
          </thead>
          <tbody>
            {items.length === 0 ? (
              <tr>
                <td colSpan={canEdit ? 11 : 10} className="px-4 py-8 text-center">
                  <Package className="w-8 h-8 text-n-300 mx-auto mb-2" />
                  <p className="text-xs text-n-500">No BOQ items yet. Send BOQ to purchase from the project page.</p>
                </td>
              </tr>
            ) : (
              items.map((item) => {
                const isAssignable = item.procurement_status === 'yet_to_place';
                const isEditing = editingId === item.id;
                return (
                  <React.Fragment key={item.id}>
                    <tr className="border-b border-n-100 hover:bg-n-50">
                      <td className="px-2 py-1.5">
                        {isAssignable && !isEditing && (
                          <input
                            type="checkbox"
                            checked={selected.has(item.id)}
                            onChange={() => toggleSelect(item.id)}
                            className="h-3 w-3"
                          />
                        )}
                      </td>
                      <td className="px-2 py-1 text-[10px] font-mono text-n-400">{item.line_number}</td>
                      <td className="px-2 py-1 text-[11px] font-medium text-n-800">
                        {(item.item_category || '').replace(/_/g, ' ')}
                      </td>
                      <td className="px-2 py-1 text-[11px] text-n-700 max-w-[240px] truncate" title={item.item_description}>
                        {item.item_description}
                      </td>
                      <td className="px-2 py-1 text-[10px] text-n-400 font-mono">{item.hsn_code ?? '—'}</td>

                      {/* Qty — editable */}
                      <td className="px-2 py-1 text-[11px] text-right font-mono">
                        {isEditing ? (
                          <input
                            type="number"
                            value={draft.quantity}
                            onChange={(e) => setDraft((d) => ({ ...d, quantity: e.target.value }))}
                            className="w-16 h-6 text-[11px] border border-p-300 rounded px-1 text-right"
                            min="0.001"
                            step="any"
                            autoFocus
                          />
                        ) : (
                          <>{item.quantity} {item.unit}</>
                        )}
                      </td>

                      {/* Rate — editable */}
                      <td className="px-2 py-1 text-[11px] text-right font-mono">
                        {isEditing ? (
                          <input
                            type="number"
                            value={draft.rate}
                            onChange={(e) => setDraft((d) => ({ ...d, rate: e.target.value }))}
                            className="w-20 h-6 text-[11px] border border-p-300 rounded px-1 text-right"
                            min="0"
                            step="any"
                          />
                        ) : (
                          formatINR(Number(item.unit_price))
                        )}
                      </td>

                      <td className="px-2 py-1 text-[11px] text-right font-mono font-medium">
                        {formatINR(Number(item.total_price))}
                      </td>
                      <td className="px-2 py-1"><StatusPill status={item.procurement_status} /></td>
                      <td className="px-2 py-1 text-[10px] text-n-600">{item.vendor_name ?? '—'}</td>

                      {/* Edit column */}
                      {canEdit && (
                        <td className="px-2 py-1 text-right">
                          {isEditing ? (
                            <div className="inline-flex items-center gap-1">
                              <button
                                className="text-green-600 hover:text-green-800 disabled:opacity-50"
                                onClick={() => saveEdit(item)}
                                disabled={editSaving}
                                title="Save"
                              >
                                <Check className="h-3.5 w-3.5" />
                              </button>
                              <button
                                className="text-n-400 hover:text-n-600"
                                onClick={cancelEdit}
                                disabled={editSaving}
                                title="Cancel"
                              >
                                <X className="h-3.5 w-3.5" />
                              </button>
                            </div>
                          ) : isAssignable ? (
                            <button
                              className="text-n-400 hover:text-n-700"
                              onClick={() => startEdit(item)}
                              title="Edit quantity and rate"
                            >
                              <Pencil className="h-3.5 w-3.5" />
                            </button>
                          ) : (
                            <button
                              className="text-n-200 cursor-not-allowed"
                              title={`Cannot edit — item is ${item.procurement_status.replace(/_/g, ' ')}`}
                              disabled
                            >
                              <Pencil className="h-3.5 w-3.5" />
                            </button>
                          )}
                        </td>
                      )}
                    </tr>
                    {/* Inline edit error row */}
                    {isEditing && editError && (
                      <tr>
                        <td colSpan={canEdit ? 11 : 10} className="px-3 py-1 text-[10px] text-red-600 bg-red-50">
                          {editError}
                        </td>
                      </tr>
                    )}
                  </React.Fragment>
                );
              })
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}
