'use server';

import { createClient } from '@repo/supabase/server';
import { revalidatePath } from 'next/cache';
import { ok, err, type ActionResult } from '@/lib/types/actions';
import type { Database } from '@repo/types/database';
import { emitErpEvent } from '@/lib/n8n/emit';

type ExpenseInsert = Database['public']['Tables']['expenses']['Insert'];
type ExpenseUpdate = Database['public']['Tables']['expenses']['Update'];

interface CallerContext {
  userId: string;
  role: string | null;
  employeeId: string | null;
}

async function getCaller(): Promise<CallerContext> {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { userId: '', role: null, employeeId: null };

  const [{ data: profile }, { data: employee }] = await Promise.all([
    supabase.from('profiles').select('role').eq('id', user.id).maybeSingle(),
    supabase.from('employees').select('id').eq('profile_id', user.id).maybeSingle(),
  ]);

  return {
    userId: user.id,
    role: profile?.role ?? null,
    employeeId: employee?.id ?? null,
  };
}

const STORAGE_BUCKET = 'project-files';

export async function submitExpense(input: {
  projectId: string | null;
  categoryId: string;
  description: string;
  amount: number;
  expenseDate?: string | null;
}): Promise<ActionResult<{ id: string; voucherNumber: string }>> {
  const op = '[submitExpense]';
  if (!input.categoryId) return err('Category is required');
  if (!input.description.trim()) return err('Description is required');
  if (!Number.isFinite(input.amount) || input.amount <= 0) {
    return err('Amount must be a positive number');
  }

  const caller = await getCaller();
  if (!caller.userId) return err('Not authenticated');
  if (!caller.employeeId) return err('No employee record — contact HR');
  if (caller.role === 'customer') return err('Customers cannot submit expenses');

  const supabase = await createClient();
  const payload: ExpenseInsert = {
    project_id: input.projectId,
    category_id: input.categoryId,
    description: input.description.trim(),
    amount: input.amount,
    expense_date: input.expenseDate ?? new Date().toISOString().slice(0, 10),
    status: 'submitted',
    submitted_by: caller.employeeId,
    submitted_at: new Date().toISOString(),
    // voucher_number is generated by the BEFORE INSERT trigger; pass '' so the trigger fills it.
    voucher_number: '',
  };

  const { data, error } = await supabase
    .from('expenses')
    .insert(payload)
    .select('id, voucher_number')
    .single();

  if (error) {
    console.error(`${op} failed`, { input, error });
    return err(error.message, error.code);
  }

  revalidatePath('/expenses');
  if (input.projectId) revalidatePath(`/projects/${input.projectId}`);

  void emitExpenseSubmitted(data.id, supabase);

  return ok({ id: data.id, voucherNumber: data.voucher_number });
}

async function emitExpenseSubmitted(
  expenseId: string,
  supabase: Awaited<ReturnType<typeof createClient>>,
): Promise<void> {
  const op = '[emitExpenseSubmitted]';
  try {
    const { data: enriched } = await supabase
      .from('expenses')
      .select(`
        id,
        voucher_number,
        amount,
        description,
        expense_date,
        expense_categories!expenses_category_id_fkey ( label ),
        projects!expenses_project_id_fkey ( project_number ),
        submitter:employees!expenses_submitted_by_fkey ( id, full_name, reporting_to_id )
      `)
      .eq('id', expenseId)
      .single();
    if (!enriched) return;

    const submitter = Array.isArray(enriched.submitter) ? enriched.submitter[0] : enriched.submitter;
    const category = Array.isArray(enriched.expense_categories) ? enriched.expense_categories[0] : enriched.expense_categories;
    const project = Array.isArray(enriched.projects) ? enriched.projects[0] : enriched.projects;

    let managerName: string | null = null;
    let managerPhone: string | null = null;
    if (submitter?.reporting_to_id) {
      const { data: manager } = await supabase
        .from('employees')
        .select('full_name, personal_phone')
        .eq('id', submitter.reporting_to_id)
        .single();
      managerName = manager?.full_name ?? null;
      managerPhone = manager?.personal_phone ?? null;
    }

    await emitErpEvent('expense_claim.submitted', {
      expense_claim_id: enriched.id,
      voucher_number: enriched.voucher_number,
      employee_name: submitter?.full_name ?? null,
      amount_inr: enriched.amount,
      category: category?.label ?? null,
      purpose: enriched.description,
      project_code: project?.project_number ?? null,
      manager_name: managerName,
      manager_whatsapp: managerPhone,
      erp_url: `https://erp.shiroienergy.com/expenses/${enriched.id}`,
    });
  } catch (e) {
    console.error(`${op} enrichment failed (non-blocking)`, {
      expenseId,
      error: e instanceof Error ? e.message : String(e),
    });
  }
}

export async function updateExpense(
  id: string,
  patch: {
    description?: string;
    amount?: number;
    expenseDate?: string;
    categoryId?: string;
    projectId?: string | null;
  },
): Promise<ActionResult<void>> {
  const op = '[updateExpense]';
  const supabase = await createClient();
  const update: ExpenseUpdate = { updated_at: new Date().toISOString() };
  if (patch.description !== undefined) update.description = patch.description.trim();
  if (patch.amount !== undefined) {
    if (!Number.isFinite(patch.amount) || patch.amount <= 0) return err('Amount must be positive');
    update.amount = patch.amount;
  }
  if (patch.expenseDate !== undefined) update.expense_date = patch.expenseDate;
  if (patch.categoryId !== undefined) update.category_id = patch.categoryId;
  if (patch.projectId !== undefined) update.project_id = patch.projectId;

  const { error } = await supabase.from('expenses').update(update).eq('id', id);
  if (error) {
    console.error(`${op} failed`, { id, patch, error });
    return err(error.message, error.code);
  }
  revalidatePath('/expenses');
  revalidatePath(`/expenses/${id}`);
  return ok(undefined as void);
}

export async function verifyExpense(id: string): Promise<ActionResult<void>> {
  const op = '[verifyExpense]';
  const caller = await getCaller();
  if (!caller.userId) return err('Not authenticated');

  const supabase = await createClient();
  // Guard: general expenses skip verify.
  const { data: row } = await supabase
    .from('expenses')
    .select('project_id, status')
    .eq('id', id)
    .maybeSingle();
  if (!row) return err('Expense not found');
  if (row.project_id === null) return err('General expenses skip the Verify stage');
  if (row.status !== 'submitted') return err(`Cannot verify — status is ${row.status}`);

  const { error } = await supabase
    .from('expenses')
    .update({
      status: 'verified',
      verified_by: caller.employeeId,
      verified_at: new Date().toISOString(),
    })
    .eq('id', id);
  if (error) {
    console.error(`${op} failed`, { id, error });
    return err(error.message, error.code);
  }
  revalidatePath('/expenses');
  revalidatePath(`/expenses/${id}`);
  if (row.project_id) revalidatePath(`/projects/${row.project_id}`);
  return ok(undefined as void);
}

export async function approveExpense(id: string): Promise<ActionResult<void>> {
  const op = '[approveExpense]';
  const caller = await getCaller();
  if (caller.role !== 'founder') return err('Only the Founder can approve expenses');

  const supabase = await createClient();
  const { data: row } = await supabase
    .from('expenses')
    .select('project_id, status')
    .eq('id', id)
    .maybeSingle();
  if (!row) return err('Expense not found');

  // Project-linked: must be verified. General: must be submitted.
  if (row.project_id === null) {
    if (row.status !== 'submitted') return err(`Cannot approve — status is ${row.status}`);
  } else {
    if (row.status !== 'verified') return err(`Cannot approve — status is ${row.status} (must be verified)`);
  }

  const { error } = await supabase
    .from('expenses')
    .update({
      status: 'approved',
      approved_by: caller.employeeId,
      approved_at: new Date().toISOString(),
    })
    .eq('id', id);
  if (error) {
    console.error(`${op} failed`, { id, error });
    return err(error.message, error.code);
  }
  revalidatePath('/expenses');
  revalidatePath(`/expenses/${id}`);
  if (row.project_id) revalidatePath(`/projects/${row.project_id}`);
  return ok(undefined as void);
}

export async function rejectExpense(id: string, reason: string): Promise<ActionResult<void>> {
  const op = '[rejectExpense]';
  if (!reason.trim()) return err('Rejection reason is required');

  const caller = await getCaller();
  if (caller.userId === '') return err('Not authenticated');

  const supabase = await createClient();
  const { data: row } = await supabase
    .from('expenses')
    .select('project_id, status')
    .eq('id', id)
    .maybeSingle();
  if (!row) return err('Expense not found');
  if (!row.status || !['submitted', 'verified'].includes(row.status)) {
    return err(`Cannot reject — status is ${row.status ?? 'unknown'}`);
  }

  // PMs can only reject project-linked submitted rows.
  if (caller.role === 'project_manager') {
    if (row.project_id === null) return err('PM cannot reject general expenses');
    if (row.status !== 'submitted') return err('PM can only reject from submitted');
  } else if (caller.role !== 'founder') {
    return err('Only PM or Founder can reject');
  }

  const { error } = await supabase
    .from('expenses')
    .update({
      status: 'rejected',
      rejected_by: caller.employeeId,
      rejected_at: new Date().toISOString(),
      rejected_reason: reason.trim(),
    })
    .eq('id', id);
  if (error) {
    console.error(`${op} failed`, { id, error });
    return err(error.message, error.code);
  }
  revalidatePath('/expenses');
  revalidatePath(`/expenses/${id}`);
  if (row.project_id) revalidatePath(`/projects/${row.project_id}`);
  return ok(undefined as void);
}

export async function deleteExpense(id: string): Promise<ActionResult<void>> {
  const op = '[deleteExpense]';
  const supabase = await createClient();
  // RLS handles authorization. Delete related documents cascade via FK.
  const { error } = await supabase.from('expenses').delete().eq('id', id);
  if (error) {
    console.error(`${op} failed`, { id, error });
    return err(error.message, error.code);
  }
  revalidatePath('/expenses');
  return ok(undefined as void);
}

export async function revertExpense(
  id: string,
  target: 'submitted' | 'verified',
): Promise<ActionResult<void>> {
  const op = '[revertExpense]';
  const caller = await getCaller();
  if (caller.role !== 'founder') return err('Only Founder can revert');

  const supabase = await createClient();
  const { data: row } = await supabase
    .from('expenses')
    .select('project_id, status')
    .eq('id', id)
    .maybeSingle();
  if (!row) return err('Expense not found');

  // Constraint: general expenses cannot be 'verified' — they have no verified stage.
  if (target === 'verified' && row.project_id === null) {
    return err('General expenses cannot be in verified state');
  }

  const update: ExpenseUpdate = { status: target, updated_at: new Date().toISOString() };
  // Clear the stage fields after the target.
  if (target === 'submitted') {
    update.verified_by = null;
    update.verified_at = null;
    update.approved_by = null;
    update.approved_at = null;
    update.rejected_by = null;
    update.rejected_at = null;
    update.rejected_reason = null;
  } else if (target === 'verified') {
    update.approved_by = null;
    update.approved_at = null;
    update.rejected_by = null;
    update.rejected_at = null;
    update.rejected_reason = null;
  }

  const { error } = await supabase.from('expenses').update(update).eq('id', id);
  if (error) {
    console.error(`${op} failed`, { id, target, error });
    return err(error.message, error.code);
  }
  revalidatePath('/expenses');
  revalidatePath(`/expenses/${id}`);
  return ok(undefined as void);
}

export async function uploadExpenseDocument(input: {
  expenseId: string;
  filePath: string;
  fileName?: string | null;
  fileSize?: number | null;
  mimeType?: string | null;
}): Promise<ActionResult<{ id: string }>> {
  const op = '[uploadExpenseDocument]';
  const caller = await getCaller();
  if (!caller.employeeId) return err('Not authenticated');
  const supabase = await createClient();
  const { data, error } = await supabase
    .from('expense_documents')
    .insert({
      expense_id: input.expenseId,
      file_path: input.filePath,
      file_name: input.fileName ?? null,
      file_size: input.fileSize ?? null,
      mime_type: input.mimeType ?? null,
      uploaded_by: caller.employeeId,
    })
    .select('id')
    .single();
  if (error) {
    console.error(`${op} failed`, { input, error });
    return err(error.message, error.code);
  }
  revalidatePath(`/expenses/${input.expenseId}`);
  return ok({ id: data.id });
}

export async function deleteExpenseDocument(id: string, expenseId: string): Promise<ActionResult<void>> {
  const op = '[deleteExpenseDocument]';
  const supabase = await createClient();
  // Fetch path before delete so we can remove storage object too.
  const { data: row } = await supabase
    .from('expense_documents')
    .select('file_path')
    .eq('id', id)
    .maybeSingle();
  const { error } = await supabase.from('expense_documents').delete().eq('id', id);
  if (error) {
    console.error(`${op} failed`, { id, error });
    return err(error.message, error.code);
  }
  if (row?.file_path) {
    await supabase.storage.from(STORAGE_BUCKET).remove([row.file_path]);
  }
  revalidatePath(`/expenses/${expenseId}`);
  return ok(undefined as void);
}
