/**
 * payment-followups-queries.ts - reads open payment_followup + payment_escalation
 * tasks for the /payments Follow-ups tab.
 *
 * Created for the Marketing + Design revamp (migration 052). The underlying
 * task rows are generated by the new per-milestone SLA version of
 * create_payment_followup_tasks() plus the hourly enqueue_payment_escalations()
 * pg_cron job.
 */

import { createClient } from '@repo/supabase/server';
import type { Database } from '@repo/types/database';

type Task = Database['public']['Tables']['tasks']['Row'];

export interface PaymentFollowupRow {
  id: string;
  title: string;
  description: string | null;
  category: string | null;
  priority: string;
  due_date: string | null;
  is_completed: boolean;
  completed_at: string | null;
  created_at: string;
  project_id: string | null;
  project_number: string | null;
  project_customer_name: string | null;
  project_status: string | null;
  assigned_to_name: string | null;
  days_old: number;
}

export interface PaymentFollowupSummary {
  total_open: number;
  total_overdue: number;
  total_escalated: number;
}

/**
 * All open payment follow-up and escalation tasks, newest first.
 * Only includes tasks where category IN (payment_followup, payment_escalation).
 */
export async function getPaymentFollowups(): Promise<PaymentFollowupRow[]> {
  const op = '[getPaymentFollowups]';
  try {
    const supabase = await createClient();

    const { data, error } = await supabase
      .from('tasks')
      .select(
        `
        id, title, description, category, priority, due_date, is_completed, completed_at, created_at,
        project_id,
        projects!tasks_project_id_fkey(project_number, customer_name, status),
        assigned_employee:employees!tasks_assigned_to_fkey(full_name)
      `,
      )
      .in('category', ['payment_followup', 'payment_escalation'])
      .eq('is_completed', false)
      .is('deleted_at', null)
      .order('created_at', { ascending: false })
      .limit(200);

    if (error) {
      console.error(`${op} query failed`, { code: error.code, message: error.message });
      throw new Error(`Failed to fetch payment follow-ups: ${error.message}`);
    }

    const now = Date.now();

    return (data ?? []).map((row) => {
      const project = row.projects as unknown as
        | { project_number: string; customer_name: string; status: string }
        | null;
      const assignedEmp = row.assigned_employee as unknown as { full_name: string } | null;
      const createdAt = new Date(row.created_at).getTime();
      const daysOld = Math.floor((now - createdAt) / (1000 * 60 * 60 * 24));

      return {
        id: row.id,
        title: row.title,
        description: row.description,
        category: row.category,
        priority: row.priority,
        due_date: row.due_date,
        is_completed: row.is_completed,
        completed_at: row.completed_at,
        created_at: row.created_at,
        project_id: row.project_id,
        project_number: project?.project_number ?? null,
        project_customer_name: project?.customer_name ?? null,
        project_status: project?.status ?? null,
        assigned_to_name: assignedEmp?.full_name ?? null,
        days_old: daysOld,
      };
    });
  } catch (e) {
    console.error(`${op} threw`, e);
    throw e;
  }
}

export async function getPaymentFollowupsSummary(): Promise<PaymentFollowupSummary> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from('tasks')
    .select('id, category, due_date')
    .in('category', ['payment_followup', 'payment_escalation'])
    .eq('is_completed', false)
    .is('deleted_at', null);

  if (error || !data) {
    return { total_open: 0, total_overdue: 0, total_escalated: 0 };
  }

  const today = new Date().toISOString().split('T')[0]!;
  const total_open = data.length;
  const total_overdue = data.filter((t) => t.due_date && t.due_date < today).length;
  const total_escalated = data.filter((t) => t.category === 'payment_escalation').length;

  return { total_open, total_overdue, total_escalated };
}
