-- ============================================================
-- Migration 003a — Proposals Core
-- File: supabase/migrations/003a_proposals_core.sql
-- Description: Core proposal table, BOM lines, simulation
--              results, and proposal revisions.
-- Date: 2026-03-29
-- Rollback:
--   DROP TABLE IF EXISTS proposal_simulations CASCADE;
--   DROP TABLE IF EXISTS proposal_bom_lines CASCADE;
--   DROP TABLE IF EXISTS proposal_revisions CASCADE;
--   DROP TABLE IF EXISTS proposals CASCADE;
--   DROP TYPE IF EXISTS proposal_status;
-- Dependencies: 001_foundation.sql, 002a_leads_core.sql
-- ============================================================

BEGIN;

-- ------------------------------------------------------------
-- 1. Enums for proposals domain
-- ------------------------------------------------------------
CREATE TYPE proposal_status AS ENUM (
  'draft',
  'sent',
  'viewed',
  'negotiating',
  'accepted',
  'rejected',
  'expired',
  'superseded'
);

CREATE TYPE gst_type AS ENUM (
  'supply',       -- Equipment supply: 5% GST (HSN 8541)
  'works_contract' -- Installation works contract: 18% GST
);

CREATE TYPE scope_owner AS ENUM (
  'shiroi',
  'client',
  'builder',
  'excluded'
);


-- ------------------------------------------------------------
-- 2. proposals
-- Core proposal record. One proposal per lead typically,
-- but revisions are tracked in proposal_revisions.
-- Numbering: SHIROI/PROP/2025-26/0042/R1
-- ------------------------------------------------------------
CREATE TABLE proposals (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_id                 UUID NOT NULL REFERENCES leads(id) ON DELETE RESTRICT,

  -- Reference number
  proposal_number         TEXT NOT NULL UNIQUE,
  -- Format: SHIROI/PROP/YYYY-YY/NNNN — generated by DB sequence.
  revision_number         INT NOT NULL DEFAULT 1,
  -- R1, R2 etc. Increments on every revision.

  -- Prepared by
  prepared_by             UUID NOT NULL REFERENCES employees(id),
  reviewed_by             UUID REFERENCES employees(id),

  -- System specification (confirmed at proposal stage)
  system_size_kwp         NUMERIC(6,2) NOT NULL,
  system_type             system_type NOT NULL,
  panel_brand             TEXT,
  panel_model             TEXT,
  panel_wattage           INT,
  panel_count             INT,
  inverter_brand          TEXT,
  inverter_model          TEXT,
  inverter_capacity_kw    NUMERIC(6,2),
  battery_brand           TEXT,
  battery_model           TEXT,
  battery_capacity_kwh    NUMERIC(6,2),
  -- NULL for on-grid systems.
  structure_type          TEXT,

  -- Financial summary (computed from BOM lines — stored for fast reads)
  subtotal_supply         NUMERIC(14,2) NOT NULL DEFAULT 0,
  subtotal_works          NUMERIC(14,2) NOT NULL DEFAULT 0,
  gst_supply_amount       NUMERIC(14,2) NOT NULL DEFAULT 0,
  -- 5% of subtotal_supply
  gst_works_amount        NUMERIC(14,2) NOT NULL DEFAULT 0,
  -- 18% of subtotal_works
  total_before_discount   NUMERIC(14,2) NOT NULL DEFAULT 0,
  discount_amount         NUMERIC(14,2) NOT NULL DEFAULT 0,
  total_after_discount    NUMERIC(14,2) NOT NULL DEFAULT 0,
  -- This is what the customer pays. Stored, never computed on read.

  -- Margin (Shiroi scope only — excludes client/builder scope)
  shiroi_cost             NUMERIC(14,2) NOT NULL DEFAULT 0,
  shiroi_revenue          NUMERIC(14,2) NOT NULL DEFAULT 0,
  gross_margin_amount     NUMERIC(14,2) NOT NULL DEFAULT 0,
  gross_margin_pct        NUMERIC(5,2) NOT NULL DEFAULT 0,

  -- Margin approval
  -- Below ₹5L auto-approved if within band.
  -- Above ₹10L requires founder approval.
  margin_approval_required BOOLEAN NOT NULL DEFAULT FALSE,
  margin_approved_by      UUID REFERENCES employees(id),
  margin_approved_at      TIMESTAMPTZ,

  -- Validity
  valid_until             DATE NOT NULL,
  -- Proposals valid 30 days from sent_at.
  -- <7 days expired: honour old price.
  -- >7 days expired: auto-requote.
  sent_at                 TIMESTAMPTZ,
  viewed_at               TIMESTAMPTZ,

  -- Status
  status                  proposal_status NOT NULL DEFAULT 'draft',
  status_updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Acceptance
  accepted_at             TIMESTAMPTZ,
  accepted_by_name        TEXT,
  acceptance_method       TEXT CHECK (acceptance_method IN (
    'otp_verified', 'physical_signature', 'email_confirmation'
  )),

  -- Rejection
  rejected_at             TIMESTAMPTZ,
  rejection_reason        TEXT,

  -- Current PDF
  current_pdf_storage_path TEXT,
  -- Full generated_documents FK added after that table is created (Migration 015).

  -- HubSpot migration
  hubspot_deal_id         TEXT,
  -- Populated during data migration only.

  notes                   TEXT,

  -- Immutable once accepted — Tier 3 from acceptance onwards
  created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER proposals_updated_at
  BEFORE UPDATE ON proposals
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Sequence for proposal numbering
CREATE SEQUENCE proposal_number_seq START 1;

CREATE INDEX idx_proposals_lead      ON proposals(lead_id);
CREATE INDEX idx_proposals_status    ON proposals(status);
CREATE INDEX idx_proposals_prepared  ON proposals(prepared_by);
CREATE INDEX idx_proposals_valid     ON proposals(valid_until) WHERE status = 'sent';
CREATE INDEX idx_proposals_number    ON proposals(proposal_number);


-- ------------------------------------------------------------
-- 3. proposal_revisions
-- Every time a proposal is revised, the old version is
-- recorded here before the new one overwrites it.
-- Immutable — Tier 3.
-- ------------------------------------------------------------
CREATE TABLE proposal_revisions (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  proposal_id         UUID NOT NULL REFERENCES proposals(id) ON DELETE CASCADE,

  revision_number     INT NOT NULL,
  revised_by          UUID NOT NULL REFERENCES employees(id),
  revision_reason     TEXT NOT NULL,

  -- Snapshot of key financials at time of revision
  total_amount        NUMERIC(14,2) NOT NULL,
  gross_margin_pct    NUMERIC(5,2) NOT NULL,
  system_size_kwp     NUMERIC(6,2) NOT NULL,

  pdf_storage_path    TEXT,
  -- PDF of this revision stored permanently.

  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
  -- Immutable. No updated_at.
);

CREATE INDEX idx_proposal_revisions_proposal ON proposal_revisions(proposal_id, revision_number DESC);


-- ------------------------------------------------------------
-- 4. proposal_bom_lines
-- Every line item in the bill of materials.
-- Scope owner determines if it's in Shiroi's revenue/cost.
-- ------------------------------------------------------------
CREATE TABLE proposal_bom_lines (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  proposal_id           UUID NOT NULL REFERENCES proposals(id) ON DELETE CASCADE,

  -- Line item
  line_number           INT NOT NULL,
  -- Display order in proposal.
  item_category         TEXT NOT NULL CHECK (item_category IN (
    'panel', 'inverter', 'battery', 'structure',
    'dc_cable', 'ac_cable', 'conduit', 'earthing',
    'acdb', 'dcdb', 'net_meter', 'civil_work',
    'installation_labour', 'transport', 'other'
  )),
  item_description      TEXT NOT NULL,
  brand                 TEXT,
  model                 TEXT,
  hsn_code              TEXT,

  -- Quantity and pricing
  quantity              NUMERIC(10,3) NOT NULL,
  unit                  TEXT NOT NULL,
  -- 'nos', 'kw', 'sqft', 'meter', 'lumpsum'
  unit_price            NUMERIC(14,2) NOT NULL,
  total_price           NUMERIC(14,2) NOT NULL,
  -- total_price = quantity * unit_price. Stored explicitly.

  -- GST
  gst_type              gst_type NOT NULL,
  gst_rate              NUMERIC(5,2) NOT NULL,
  -- 5.00 for supply, 18.00 for works contract.
  gst_amount            NUMERIC(14,2) NOT NULL,

  -- Scope
  scope_owner           scope_owner NOT NULL DEFAULT 'shiroi',
  -- shiroi: in Shiroi's revenue and cost.
  -- client: shown for customer's budgeting, excluded from Shiroi total.
  -- builder: builder's responsibility, excluded.
  -- excluded: explicitly out of scope.

  -- BOM correction factors
  raw_estimated_cost    NUMERIC(14,2),
  -- Before correction factor applied.
  correction_factor     NUMERIC(6,4),
  -- From bom_correction_factors table. e.g. 1.0850 = 8.5% correction.
  corrected_cost        NUMERIC(14,2),
  -- raw_estimated_cost * correction_factor. This is what Shiroi uses for margin calc.
  correction_overridden BOOLEAN NOT NULL DEFAULT FALSE,
  override_reason       TEXT,
  -- Mandatory if correction_overridden = TRUE.

  notes                 TEXT,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER proposal_bom_lines_updated_at
  BEFORE UPDATE ON proposal_bom_lines
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE INDEX idx_bom_lines_proposal  ON proposal_bom_lines(proposal_id, line_number);
CREATE INDEX idx_bom_lines_category  ON proposal_bom_lines(item_category);
CREATE INDEX idx_bom_lines_scope     ON proposal_bom_lines(scope_owner);


-- ------------------------------------------------------------
-- 5. proposal_simulations
-- PVWatts/PVLib simulation results stored per proposal.
-- Both simulation sources always stored when available.
-- Primary: PVWatts. Fallback: PVLib microservice.
-- ------------------------------------------------------------
CREATE TABLE proposal_simulations (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  proposal_id           UUID NOT NULL REFERENCES proposals(id) ON DELETE CASCADE,

  -- Input parameters
  latitude              NUMERIC(9,6) NOT NULL,
  longitude             NUMERIC(9,6) NOT NULL,
  system_capacity_kw    NUMERIC(6,2) NOT NULL,
  tilt_degrees          NUMERIC(5,2) NOT NULL DEFAULT 10,
  azimuth_degrees       NUMERIC(6,2) NOT NULL DEFAULT 180,
  -- 180 = south-facing. Standard for Indian installations.
  losses_pct            NUMERIC(5,2) NOT NULL DEFAULT 14,
  -- PVWatts default system losses.

  -- Source
  simulation_source     TEXT NOT NULL CHECK (simulation_source IN (
    'pvwatts', 'pvlib'
  )),
  api_response_raw      JSONB,
  -- Full API response stored for audit and debugging.

  -- Annual output
  annual_kwh            NUMERIC(10,2) NOT NULL,
  -- P50/P75/P90 available from PVLib only.
  p50_annual_kwh        NUMERIC(10,2),
  p75_annual_kwh        NUMERIC(10,2),
  p90_annual_kwh        NUMERIC(10,2),

  -- Monthly breakdown (array of 12 values)
  monthly_kwh           NUMERIC(10,2)[] NOT NULL,
  -- Index 0 = January, Index 11 = December.

  -- Degradation-adjusted outputs shown in proposal
  year1_kwh             NUMERIC(10,2),
  year5_kwh             NUMERIC(10,2),
  year10_kwh            NUMERIC(10,2),
  year25_kwh            NUMERIC(10,2),
  degradation_rate_pct  NUMERIC(4,2) DEFAULT 0.60,
  -- Typical 0.5–0.7%/year panel degradation.

  -- Financial projections
  tariff_rate           NUMERIC(6,2) NOT NULL,
  -- ₹/kWh used for savings calculation.
  annual_savings_yr1    NUMERIC(14,2),
  payback_years         NUMERIC(5,2),

  is_primary            BOOLEAN NOT NULL DEFAULT TRUE,
  -- Only one simulation is primary per proposal.
  -- If PVWatts fails and PVLib is used, PVLib becomes primary.

  simulated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
  -- Immutable once created. No updated_at.
);

CREATE INDEX idx_simulations_proposal ON proposal_simulations(proposal_id);
CREATE INDEX idx_simulations_primary  ON proposal_simulations(proposal_id)
  WHERE is_primary = TRUE;


-- ------------------------------------------------------------
-- RLS — proposals core
-- ------------------------------------------------------------
ALTER TABLE proposals ENABLE ROW LEVEL SECURITY;

CREATE POLICY "proposals_read"
  ON proposals FOR SELECT
  USING (
    (SELECT role FROM profiles WHERE id = auth.uid()) IN
      ('founder', 'hr_manager', 'finance', 'project_manager')
    OR prepared_by = (SELECT id FROM employees WHERE profile_id = auth.uid())
    OR (SELECT role FROM profiles WHERE id = auth.uid()) = 'sales_engineer'
  );

CREATE POLICY "proposals_insert"
  ON proposals FOR INSERT
  WITH CHECK (
    (SELECT role FROM profiles WHERE id = auth.uid()) IN
      ('founder', 'sales_engineer', 'project_manager')
  );

CREATE POLICY "proposals_update"
  ON proposals FOR UPDATE
  USING (
    (SELECT role FROM profiles WHERE id = auth.uid()) IN ('founder')
    OR (
      (SELECT role FROM profiles WHERE id = auth.uid()) = 'sales_engineer'
      AND status NOT IN ('accepted', 'rejected')
      -- Cannot edit accepted or rejected proposals.
    )
  );

ALTER TABLE proposal_revisions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "proposal_revisions_read"
  ON proposal_revisions FOR SELECT
  USING (
    (SELECT role FROM profiles WHERE id = auth.uid()) IN
      ('founder', 'sales_engineer', 'project_manager', 'finance')
  );

CREATE POLICY "proposal_revisions_insert"
  ON proposal_revisions FOR INSERT
  WITH CHECK (
    (SELECT role FROM profiles WHERE id = auth.uid()) IN
      ('founder', 'sales_engineer')
  );

ALTER TABLE proposal_bom_lines ENABLE ROW LEVEL SECURITY;

CREATE POLICY "bom_lines_read"
  ON proposal_bom_lines FOR SELECT
  USING (
    (SELECT role FROM profiles WHERE id = auth.uid()) IN
      ('founder', 'sales_engineer', 'project_manager', 'finance')
  );

CREATE POLICY "bom_lines_write"
  ON proposal_bom_lines FOR ALL
  USING (
    (SELECT role FROM profiles WHERE id = auth.uid()) IN
      ('founder', 'sales_engineer')
  );

ALTER TABLE proposal_simulations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "simulations_read"
  ON proposal_simulations FOR SELECT
  USING (
    (SELECT role FROM profiles WHERE id = auth.uid()) IN
      ('founder', 'sales_engineer', 'project_manager', 'finance')
  );

CREATE POLICY "simulations_insert"
  ON proposal_simulations FOR INSERT
  WITH CHECK (
    (SELECT role FROM profiles WHERE id = auth.uid()) IN
      ('founder', 'sales_engineer')
  );

COMMIT;