-- ============================================================
-- Migration 004c — Site Reports, Photos, Commissioning
-- File: supabase/migrations/004c_projects_site_reports.sql
-- Description: Daily site reports (offline-first), site photos,
--              photo gates, commissioning reports, and
--              commissioning report corrections.
-- Date: 2026-03-29
-- Rollback:
--   DROP TABLE IF EXISTS site_report_corrections CASCADE;
--   DROP TABLE IF EXISTS commissioning_reports CASCADE;
--   DROP TABLE IF EXISTS photo_gate_verifications CASCADE;
--   DROP TABLE IF EXISTS site_photos CASCADE;
--   DROP TABLE IF EXISTS daily_site_reports CASCADE;
-- Dependencies: 001_foundation.sql, 004a_projects_core.sql
-- ============================================================

BEGIN;

-- ------------------------------------------------------------
-- 1. daily_site_reports
-- Written by site supervisor every day from mobile app.
-- Offline-first: written to WatermelonDB first, synced later.
-- Tier 1 within 48h — freely editable.
-- Tier 2 after 48h — correction by new record required.
-- ------------------------------------------------------------
CREATE TABLE daily_site_reports (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  -- UUID generated on device. Enables offline creation.

  project_id            UUID NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  milestone_id          UUID REFERENCES project_milestones(id),
  submitted_by          UUID NOT NULL REFERENCES employees(id),

  report_date           DATE NOT NULL,
  -- 'YYYY-MM-DD'. Stored as DATE not TIMESTAMPTZ.
  -- Reason: "2025-03-20" means the same date everywhere.

  -- Workforce
  workers_count         INT NOT NULL DEFAULT 0,
  supervisors_count     INT NOT NULL DEFAULT 0,

  -- Weather
  weather               TEXT NOT NULL DEFAULT 'sunny' CHECK (weather IN (
    'sunny', 'partly_cloudy', 'cloudy', 'rainy', 'stormy'
  )),
  weather_delay         BOOLEAN NOT NULL DEFAULT FALSE,
  weather_delay_hours   NUMERIC(4,1),

  -- Work done today (pre-populated from completion components)
  panels_installed_today    INT NOT NULL DEFAULT 0,
  panels_installed_cumulative INT NOT NULL DEFAULT 0,
  -- Running total. Computed from all reports for this project.

  work_description      TEXT NOT NULL,
  -- Voice-to-text primary input on mobile.

  -- Milestone progress (objective facts only)
  structure_progress    TEXT CHECK (structure_progress IN (
    'not_started', 'columns_done', 'rails_done',
    'bracing_done', 'complete'
  )),
  electrical_progress   TEXT CHECK (electrical_progress IN (
    'not_started', 'inverter_mounted', 'acdb_done',
    'strings_done', 'ac_cable_done', 'complete'
  )),

  -- Issues
  issues_reported       BOOLEAN NOT NULL DEFAULT FALSE,
  issue_summary         TEXT,
  -- Full issue logged in project_issues table.

  -- Material received today
  materials_received    BOOLEAN NOT NULL DEFAULT FALSE,
  materials_summary     TEXT,

  -- Visitors on site
  pm_visited            BOOLEAN NOT NULL DEFAULT FALSE,
  other_visitors        TEXT,

  -- Correction tracking
  has_correction        BOOLEAN NOT NULL DEFAULT FALSE,
  -- Set to TRUE when a site_report_corrections record is created.
  is_locked             BOOLEAN NOT NULL DEFAULT FALSE,
  locked_at             TIMESTAMPTZ,
  -- Set to TRUE after 48h. Trigger runs nightly.

  -- AI narrative (generated from report data)
  ai_narrative          TEXT,
  -- Generated by Claude API. Plain English summary for PM.
  ai_narrative_generated_at TIMESTAMPTZ,

  -- Offline sync
  sync_status           TEXT NOT NULL DEFAULT 'local_only' CHECK (sync_status IN (
    'local_only', 'syncing', 'synced', 'sync_failed'
  )),
  created_on_device_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  -- Device timestamp at creation. May differ from created_at.

  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER daily_site_reports_updated_at
  BEFORE UPDATE ON daily_site_reports
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE UNIQUE INDEX idx_dsr_project_date
  ON daily_site_reports(project_id, report_date);
-- One report per project per day.

CREATE INDEX idx_dsr_submitted_by ON daily_site_reports(submitted_by);
CREATE INDEX idx_dsr_sync         ON daily_site_reports(sync_status)
  WHERE sync_status != 'synced';
CREATE INDEX idx_dsr_locked       ON daily_site_reports(project_id, is_locked);


-- ------------------------------------------------------------
-- 2. site_report_corrections
-- Tier 2 correction record for locked daily site reports.
-- Created when >48h has passed and a correction is needed.
-- Manager must approve. Original flagged has_correction=TRUE.
-- ------------------------------------------------------------
CREATE TABLE site_report_corrections (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  original_report_id    UUID NOT NULL REFERENCES daily_site_reports(id) ON DELETE RESTRICT,
  project_id            UUID NOT NULL REFERENCES projects(id),
  requested_by          UUID NOT NULL REFERENCES employees(id),
  approved_by           UUID REFERENCES employees(id),

  -- What changed
  field_corrected       TEXT NOT NULL,
  -- Which field was wrong. e.g. 'panels_installed_today'
  original_value        TEXT NOT NULL,
  corrected_value       TEXT NOT NULL,
  correction_reason     TEXT NOT NULL,
  -- Mandatory. Cannot be blank.

  status                TEXT NOT NULL DEFAULT 'pending' CHECK (status IN (
    'pending', 'approved', 'rejected'
  )),
  approved_at           TIMESTAMPTZ,
  rejected_reason       TEXT,

  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER site_report_corrections_updated_at
  BEFORE UPDATE ON site_report_corrections
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE INDEX idx_src_original  ON site_report_corrections(original_report_id);
CREATE INDEX idx_src_project   ON site_report_corrections(project_id);
CREATE INDEX idx_src_pending   ON site_report_corrections(status)
  WHERE status = 'pending';


-- ------------------------------------------------------------
-- 3. site_photos
-- Photos uploaded from mobile app. Offline-first.
-- Photo gates: certain milestone completions require a photo
-- before the count or checklist item is accepted.
-- ------------------------------------------------------------
CREATE TABLE site_photos (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  -- UUID generated on device.

  project_id            UUID NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  daily_report_id       UUID REFERENCES daily_site_reports(id),
  -- NULL for photos not linked to a daily report
  -- (e.g. QC gate photos, survey photos).
  uploaded_by           UUID NOT NULL REFERENCES employees(id),

  photo_type            TEXT NOT NULL CHECK (photo_type IN (
    'progress', 'material_received', 'qc_gate',
    'issue', 'commissioning', 'before_work',
    'after_work', 'survey', 'other'
  )),

  milestone_reference   TEXT,
  -- Which milestone this photo evidences.

  storage_path          TEXT NOT NULL UNIQUE,
  file_name             TEXT NOT NULL,
  file_size_bytes       BIGINT,
  mime_type             TEXT DEFAULT 'image/jpeg',

  -- GPS metadata (from mobile device)
  gps_latitude          NUMERIC(9,6),
  gps_longitude         NUMERIC(9,6),
  gps_accuracy_meters   NUMERIC(6,1),
  captured_at           TIMESTAMPTZ,
  -- Device timestamp when photo was taken.

  -- Photo gate
  is_gate_photo         BOOLEAN NOT NULL DEFAULT FALSE,
  gate_verified         BOOLEAN NOT NULL DEFAULT FALSE,
  gate_verified_by      UUID REFERENCES employees(id),
  gate_verified_at      TIMESTAMPTZ,

  -- Caption
  caption               TEXT,

  -- Offline sync
  sync_status           TEXT NOT NULL DEFAULT 'local_only' CHECK (sync_status IN (
    'local_only', 'syncing', 'synced', 'sync_failed'
  )),

  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
  -- Immutable after upload. No updated_at.
);

CREATE INDEX idx_site_photos_project ON site_photos(project_id);
CREATE INDEX idx_site_photos_report  ON site_photos(daily_report_id);
CREATE INDEX idx_site_photos_gate    ON site_photos(project_id)
  WHERE is_gate_photo = TRUE AND gate_verified = FALSE;
CREATE INDEX idx_site_photos_sync    ON site_photos(sync_status)
  WHERE sync_status != 'synced';


-- ------------------------------------------------------------
-- 4. photo_gate_verifications
-- When a photo gate is verified by PM, record is created here.
-- Unlocks the associated completion component.
-- Immutable — Tier 3.
-- ------------------------------------------------------------
CREATE TABLE photo_gate_verifications (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  site_photo_id         UUID NOT NULL REFERENCES site_photos(id),
  project_id            UUID NOT NULL REFERENCES projects(id),
  completion_component_id UUID REFERENCES project_completion_components(id),
  verified_by           UUID NOT NULL REFERENCES employees(id),

  verification_result   TEXT NOT NULL CHECK (verification_result IN (
    'approved', 'rejected'
  )),
  rejection_reason      TEXT,
  -- Required if verification_result = 'rejected'.

  verified_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
  -- Immutable. No updated_at.
);

CREATE INDEX idx_photo_gate_verif_photo   ON photo_gate_verifications(site_photo_id);
CREATE INDEX idx_photo_gate_verif_project ON photo_gate_verifications(project_id);


-- ------------------------------------------------------------
-- 5. commissioning_reports
-- Final report when system is switched on.
-- Requires customer signature (OTP or physical).
-- Immutable once signed — Tier 3.
-- ------------------------------------------------------------
CREATE TABLE commissioning_reports (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id              UUID NOT NULL UNIQUE REFERENCES projects(id) ON DELETE RESTRICT,
  prepared_by             UUID NOT NULL REFERENCES employees(id),
  witnessed_by            UUID REFERENCES employees(id),
  -- PM or senior engineer who witnessed commissioning.

  commissioning_date      DATE NOT NULL,

  -- System details at commissioning
  system_size_kwp         NUMERIC(6,2) NOT NULL,
  panel_count_installed   INT NOT NULL,
  inverter_serial_number  TEXT,
  -- Primary inverter serial number.

  -- Test results
  dc_voltage_v            NUMERIC(7,2),
  dc_current_a            NUMERIC(7,2),
  ac_voltage_v            NUMERIC(7,2),
  ac_frequency_hz         NUMERIC(5,2),
  insulation_resistance_mohm NUMERIC(8,3),
  -- IR test result. Below 0.5 MΩ → auto-create service ticket.
  earth_resistance_ohm    NUMERIC(8,3),

  -- Generation confirmed
  generation_confirmed    BOOLEAN NOT NULL DEFAULT FALSE,
  initial_reading_kwh     NUMERIC(10,3) NOT NULL DEFAULT 0,
  -- Meter reading at commissioning.

  -- QC gate 3 reference
  qc_gate3_inspection_id  UUID REFERENCES qc_gate_inspections(id),

  -- Customer handover
  customer_explained      BOOLEAN NOT NULL DEFAULT FALSE,
  -- System operation explained to customer.
  app_download_assisted   BOOLEAN NOT NULL DEFAULT FALSE,
  -- Customer app download assisted on site.

  -- Signature
  customer_name_signed    TEXT,
  customer_signed_at      TIMESTAMPTZ,
  signature_method        TEXT CHECK (signature_method IN (
    'otp_verified', 'physical_signature', 'drawn_on_device'
  )),
  signature_storage_path  TEXT,

  -- Status
  status                  TEXT NOT NULL DEFAULT 'draft' CHECK (status IN (
    'draft', 'unsigned', 'signed', 'submitted'
  )),

  -- PDF
  unsigned_pdf_path       TEXT,
  signed_pdf_path         TEXT,

  notes                   TEXT,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER commissioning_reports_updated_at
  BEFORE UPDATE ON commissioning_reports
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE INDEX idx_commissioning_project ON commissioning_reports(project_id);
CREATE INDEX idx_commissioning_status  ON commissioning_reports(status);
CREATE INDEX idx_commissioning_ir_test ON commissioning_reports(insulation_resistance_mohm)
  WHERE insulation_resistance_mohm IS NOT NULL;
-- Used to flag IR tests below 0.5 MΩ threshold.


-- ------------------------------------------------------------
-- RLS — site reports, photos, commissioning
-- ------------------------------------------------------------

ALTER TABLE daily_site_reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "dsr_read"
  ON daily_site_reports FOR SELECT
  USING (
    (SELECT role FROM profiles WHERE id = auth.uid()) IN
      ('founder', 'project_manager', 'finance')
    OR submitted_by = (SELECT id FROM employees WHERE profile_id = auth.uid())
    OR EXISTS (
      SELECT 1 FROM projects p
      WHERE p.id = daily_site_reports.project_id
        AND (
          p.project_manager_id = (SELECT id FROM employees WHERE profile_id = auth.uid())
          OR p.site_supervisor_id = (SELECT id FROM employees WHERE profile_id = auth.uid())
        )
    )
  );

CREATE POLICY "dsr_insert"
  ON daily_site_reports FOR INSERT
  WITH CHECK (
    (SELECT role FROM profiles WHERE id = auth.uid()) IN
      ('founder', 'project_manager', 'site_supervisor')
  );

CREATE POLICY "dsr_update"
  ON daily_site_reports FOR UPDATE
  USING (
    (SELECT role FROM profiles WHERE id = auth.uid()) IN ('founder', 'project_manager')
    OR (
      submitted_by = (SELECT id FROM employees WHERE profile_id = auth.uid())
      AND is_locked = FALSE
      -- Site supervisor can only edit own unlocked reports.
    )
  );

ALTER TABLE site_report_corrections ENABLE ROW LEVEL SECURITY;

CREATE POLICY "src_read"
  ON site_report_corrections FOR SELECT
  USING (
    (SELECT role FROM profiles WHERE id = auth.uid()) IN
      ('founder', 'project_manager')
    OR requested_by = (SELECT id FROM employees WHERE profile_id = auth.uid())
  );

CREATE POLICY "src_insert"
  ON site_report_corrections FOR INSERT
  WITH CHECK (
    (SELECT role FROM profiles WHERE id = auth.uid()) IN
      ('founder', 'project_manager', 'site_supervisor')
  );

CREATE POLICY "src_update"
  ON site_report_corrections FOR UPDATE
  USING (
    (SELECT role FROM profiles WHERE id = auth.uid()) IN
      ('founder', 'project_manager')
  );

ALTER TABLE site_photos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "site_photos_read"
  ON site_photos FOR SELECT
  USING (
    (SELECT role FROM profiles WHERE id = auth.uid()) IN
      ('founder', 'project_manager', 'site_supervisor', 'finance')
    OR uploaded_by = (SELECT id FROM employees WHERE profile_id = auth.uid())
  );

CREATE POLICY "site_photos_insert"
  ON site_photos FOR INSERT
  WITH CHECK (
    (SELECT role FROM profiles WHERE id = auth.uid()) IN
      ('founder', 'project_manager', 'site_supervisor')
  );

ALTER TABLE photo_gate_verifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "photo_gate_verif_read"
  ON photo_gate_verifications FOR SELECT
  USING (
    (SELECT role FROM profiles WHERE id = auth.uid()) IN
      ('founder', 'project_manager', 'site_supervisor')
  );

CREATE POLICY "photo_gate_verif_insert"
  ON photo_gate_verifications FOR INSERT
  WITH CHECK (
    (SELECT role FROM profiles WHERE id = auth.uid()) IN
      ('founder', 'project_manager')
  );

ALTER TABLE commissioning_reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "commissioning_read"
  ON commissioning_reports FOR SELECT
  USING (
    (SELECT role FROM profiles WHERE id = auth.uid()) IN
      ('founder', 'project_manager', 'site_supervisor', 'finance')
    OR EXISTS (
      SELECT 1 FROM projects p
      WHERE p.id = commissioning_reports.project_id
        AND p.customer_profile_id = auth.uid()
    )
  );

CREATE POLICY "commissioning_insert"
  ON commissioning_reports FOR INSERT
  WITH CHECK (
    (SELECT role FROM profiles WHERE id = auth.uid()) IN
      ('founder', 'project_manager', 'site_supervisor')
  );

CREATE POLICY "commissioning_update"
  ON commissioning_reports FOR UPDATE
  USING (
    (SELECT role FROM profiles WHERE id = auth.uid()) IN
      ('founder', 'project_manager')
    AND status != 'signed'
    -- Cannot update once customer has signed.
  );

COMMIT;